In [3]:
from get_b3_data import B3PublicData
import pandas as pd
import numpy as np
import glob
import os
pd.set_option('display.max_columns', None)

In [3]:
# COLS = ['DATA',	'CODBDI', 'TICKER', 'TPMERC', 'NOMRES', 'ABERTURA', 'MAXIMO', 'MINIMO', 'FECHAMENTO', 'VOL_TOTAL']
# anos = range(2015, 2026)
# b3 = B3PublicData()

# for ano in anos:
#     df = b3.read_df_year(ano)
#     os.makedirs(f"raw/data/{ano}", exist_ok=True)
#     df[COLS].to_parquet(f"data/raw/{ano}/cotahist_{ano}.parquet")

In [4]:
# pastas = os.listdir("data/raw/")
# dfs = []
# for pasta in pastas:
#     file = f'data/raw/{pasta}/cotahist_{pasta}.parquet'
#     dfs.append(pd.read_parquet(file))

In [5]:
# df_base = pd.concat(dfs)a
df_base = pd.read_parquet('data/processed/df_base.parquet')
df_base.loc[df_base['TICKER'] == 'CCRO3', 'TICKER'] = 'MOTV3'
df_base.loc[df_base['TICKER'] == 'CVBI11', 'TICKER'] = 'PCIP11'
df_base.loc[df_base['TICKER'] == 'ELET3', 'TICKER'] = 'AXIA3'
df_base.loc[df_base['TICKER'] == 'ELET6', 'TICKER'] = 'AXIA6'
df_base.loc[df_base['TICKER'] == 'EMBR3', 'TICKER'] = 'EMBJ3'
df_base.loc[df_base['TICKER'] == 'JBSS3', 'TICKER'] = 'JBSS32'
df_base.loc[df_base['TICKER'] == 'LVTC3', 'TICKER'] = 'WDCN3'
df_base.loc[df_base['TICKER'] == 'MALL11', 'TICKER'] = 'PMLL11'
df_base.loc[df_base['TICKER'] == 'MBLY3', 'TICKER'] = 'TOKY3'
df_base.loc[df_base['TICKER'] == 'NCHB11', 'TICKER'] = 'FYTO11'
df_base.loc[df_base['TICKER'] == 'NINJ3', 'TICKER'] = 'REAG3'
df_base.loc[df_base['TICKER'] == 'NTCO3', 'TICKER'] = 'NATU3'
df_base.loc[df_base['TICKER'] == 'OULG11', 'TICKER'] = 'TRUE11'
df_base.loc[df_base['TICKER'] == 'RBFF11', 'TICKER'] = 'RBFM11'
df_base.loc[df_base['TICKER'] == 'QAGR11', 'TICKER'] = 'PLAG11'
df_base.loc[df_base['TICKER'] == 'RMAI11', 'TICKER'] = 'LMAI11'
df_base.loc[df_base['TICKER'] == 'RRCI11', 'TICKER'] = 'XLPR11'
df_base.loc[df_base['TICKER'] == 'RVBI11', 'TICKER'] = 'PSEC11'
df_base.loc[df_base['TICKER'] == 'XPPR11', 'TICKER'] = 'VPPR11'
df_base.loc[df_base['TICKER'] == 'REAG3', 'TICKER'] = 'ARND3'

In [6]:
#df_base[df_base['TICKER'] == 'ARND3']

In [7]:
df_base.to_parquet('data/processed/df_base.parquet')

In [8]:
# lendo dados financeiros de 2025 para pegar os tickers que existem
# e depois filtrar para manter apenas os que existem
tickers_2025 = pd.read_parquet('data/raw/2025/cotahist_2025.parquet')['TICKER'].unique()

In [9]:
# pegando empresas com menos de 252 [1 ano de negociacao] linhas de negociação para remover
di = df_base.groupby('TICKER').size()
di = di[di <= 252].index.tolist()
# pegando tickers de empresas que entraram em recuperação judicial para remover
ticker_rec_judicial = df_base[df_base['CODBDI'] == 8]['TICKER'].unique()
tickers_dados_insuf = [
    'ADMF3', 'AETH39', 'ANGV39', 'APXR11', 'APXU11', 'ASMT11', 'ASRF11', 'AXIA5', 'AXRP39', 'BAOM39',
    'BARY39', 'BASK39', 'BBAJ39', 'BBCN39', 'BBER39', 'BBGR39', 'BBIL39', 'BBJP39', 'BBMR39'
] + di
tickers_saiu_bolsa = [
    'AZUL4', 'BPAN4', 'BPFF11', 'BRFS3', 'BTEK11', 'CCRO3', 'CLSA3', 'CPLE5', 'CPLE6', 
    'CRFB3', 'ELMD3', 'EXCO32', 'GOLL4', 'GPIV33', 'KRSA3', 'LIPR3', 'MOAR3', 'NFTS11', 
    'PORT3', 'PULV11', 'RBED11', 'RDNI3', 'SRNA3', 'STBP3', 'STOC31', 'ZAMP3',
]
df_database = df_base[
    ~df_base['TICKER'].str.endswith('34') &
    (df_base['CODBDI'].isin([2, 12, 14, 34, 35, 36])) &
    (df_base['TICKER'].isin(tickers_2025)) &
    ~(df_base['TICKER'].isin(tickers_dados_insuf)) &
    ~(df_base['TICKER'].isin(ticker_rec_judicial)) &
    ~(df_base['TICKER'].isin(tickers_saiu_bolsa))
]

In [10]:
def to_yfinance_style(
    df: pd.DataFrame,
    ticker: str | None = None,
    adjust_prices: bool = True,
) -> pd.DataFrame:
    RENAME = {
        "ABERTURA": "Open",
        "MAXIMO": "High",
        "MINIMO": "Low",
        "FECHAMENTO": "Close",
        "VOL_TOTAL": "Volume",
    }
    METRICS_ORDER = ["Close", "High", "Low", "Open", "Volume"]
    PRICE_COLS = ["Open", "High", "Low", "Close"]

    cols_needed = ["DATA", "TICKER"] + list(RENAME.keys())
    out = df[cols_needed].copy()
    out["TICKER"] = out["TICKER"].astype(str).str.upper()

    out["Date"] = pd.to_datetime(out["DATA"], format="%Y%m%d")
    out = out.drop(columns=["DATA"]).rename(columns=RENAME)

    if adjust_prices:
        out[PRICE_COLS] = out[PRICE_COLS] / 100

    out = out.set_index("Date").sort_index()
    out = out.pivot_table(
        index="Date",
        columns="TICKER",
        values=METRICS_ORDER,
        aggfunc="first",  # ou "mean" se preferir agregar duplicatas
    )
    out = out.sort_index(axis=1, level=1)
    out.columns.names = ["Price", "Ticker"]
    out.index.name = "Date"
    return out

df_final = to_yfinance_style(df_database)

In [11]:
df_final.to_parquet('data/processed/data_assets.parquet')

In [ ]:
k = pd.read_parquet('data/processed/data_assets.parquet')
# Calcular retornos log (mais estável que preço bruto)
returns = np.log(k['Close'] / k['Close'].shift(1))

c:\Users\kimbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\internals\blocks.py:395: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)

In [10]:
# o bloco de codigo abaixo funciona para filtrar a matriz de retornos
# pegando ativos que apresentem uma serie historica valida de pelo menos 
# 40% do historico, para posteriormente criar uma matriz de correlação 
# com ativos que possuam serie historica relevante
#
# obs 1: ao filtrarmos por 40% numa serie historica de 252 dias, 
# teriamos aproximadamente 1092 dias de pregao e na serie historica 
# de 2015-2025 (aproximadamente 11 anos e 2729 pregoes) seria 
# equivalente a ~4.3 anos de historico, que é um periodo razoavel
# para a a analise. (esse valor pode ser ajustado dps)
# obs 2: a serie de retornos é diaria

selected_assets = []
assets = returns.columns.tolist()
for asset in assets:
    serie = returns[asset]
    true_info = serie.notna().sum()
    if (( true_info / len(serie) ) * 100) >= 40:
        selected_assets.append(asset)

print(len(returns.columns.tolist())) # matriz de ativos com series historica gerada
print(len(selected_assets))          # ativos com series historica relevante   
selected_assets[:10]

920
511

['AALR3',
 'ABCB4',
 'ABCP11',
 'ABEV3',
 'ACWI11',
 'AERI3',
 'AFHI11',
 'AFLT3',
 'AGRO3',
 'AIEC11']

In [12]:
# Correlação — pandas já ignora NaN pairwise
corr_matrix = returns.loc[:, selected_assets].corr(method='pearson')
corr_matrix

Ticker,AALR3,ABCB4,ABCP11,ABEV3,ACWI11,AERI3,AFHI11,AFLT3,AGRO3,AIEC11,ALLD3,ALMI11,ALPA3,ALPA4,ALPK3,ALUP11,ALUP3,ALUP4,ALZR11,AMAR3,ANIM3,ARML3,ARND3,ARRI11,ASAI3,AURA33,AXIA3,AXIA6,AZEV3,AZEV4,B3SA3,BAAX39,BACW39,BARI11,BAZA3,BBAS3,BBDC3,BBDC4,BBFO11,BBOV11,BBRC11,BBSD11,BBSE3,BCHI39,BCIA11,BCRI11,BDIF11,BDIV11,BDVY39,BEEF3,BEES3,BEES4,BEWJ39,BGIP4,BIAU39,BIEF39,BIEM39,BIEU39,BIJR39,BIOM3,BITH11,BITO39,BIVB39,BIVE39,BIWM39,BIXN39,BIYW39,BLAU3,BLMG11,BMEB4,BMGB4,BMIN4,BMKS3,BMLC11,BMOB3,BNDA39,BNFS11,BOVA11,BOVB11,BOVV11,BOVX11,BPAC11,BPAC3,BPAC5,BPML11,BRAP3,BRAP4,BRAX11,BRBI11,BRCO11,BRCR11,BRKM3,BRKM5,BRSR3,BRSR6,BRZP11,BSLV39,BTAL11,BTLG11,BTRA11,CAMB3,CAML3,CARE11,CASH3,CBAV3,CBOP11,CEAB3,CEBR3,CEBR5,CEBR6,CEDO4,CEOC11,CGAS3,CGAS5,CGRA3,CGRA4,CLSC4,CMIG3,CMIG4,CMIN3,CNES11,COCE5,COGN3,CPFE3,CPFF11,CPLE3,CPTI11,CPTS11,CRFF11,CRPG5,CRPG6,CSAN3,CSED3,CSMG3,CSNA3,CTKA4,CTXT11,CURY3,CVCB3,CXCO11,CXRI11,CXSE3,CXTL11,CYRE3,DASA3,DESK3,DEVA11,DEXP3,DIRR3,DIVO11,DMVF3,DOHL4,DOTZ3,EALT4,ECOO11,ECOR3,EDGA11,EGIE3,EMAE4,EMBJ3,ENDD11,ENGI11,ENGI3,ENGI4,ENJU3,EQPA3,EQTL3,ESGB11,ESPA3,EUCA3,EUCA4,EURO11,EVEN3,EZTC3,FAED11,FATN11,FCFL11,FESA4,FIGS11,FIIB11,FIND11,FIQE3,FIVN11,FIXX11,FLCR11,FLMA11,FLRP11,FLRY3,FNAM11,FNOR11,FPAB11,FRAS3,FSRF11,FVPQ11,FYTO11,G2DI33,GCRI11,GEPA4,GFSA3,GGBR3,GGBR4,GGPS3,GGRC11,GMAT3,GOAU3,GOAU4,GOGL35,GOLD11,GOVE11,GRND3,GSFI11,GSHP3,GTWR11,GUAR3,HABT11,HAGA3,HAGA4,HAPV3,HASH11,HBOR3,HBRE3,HBSA3,HCRI11,HCTR11,HFOF11,HGBS11,HGCR11,HGFF11,HGIC11,HGLG11,HGPO11,HGRE11,HGRU11,HLOG11,HOSI11,HPDP11,HRDF11,HREC11,HSAF11,HSLG11,HSML11,HTEK11,HTMX11,HUSC11,HYPE3,IFCM3,IFRA11,INTB3,IRBR3,IRDM11,ISUS11,ITSA3,ITSA4,ITUB3,ITUB4,IVVB11,JALL3,JBSS32,JFLL11,JHSF3,JPPA11,JSLG3,JSRE11,KDIF11,KEPL3,KFOF11,KISU11,KLBN11,KLBN3,KLBN4,KNCR11,KNHY11,KNIP11,KNRE11,KNRI11,KNSC11,LAND3,LAVV3,LEVE3,LFTT11,LJQQ3,LOGG3,LOGN3,LPSB3,LREN3,LVBI11,LWSA3,MATB11,MATD3,MAXR11,MCCI11,MDIA3,MDNE3,MEAL3,MELK3,MFII11,MGHT11,MGLU3,MILL11,MILS3,MLAS3,MNDL3,MNPR3,MOTV3,MOVI3,MRFG3,MRVE3,MTRE3,MTSA4,MULT3,MXRF11,MYPK3,NASD11,NATU3,NAVT11,NEOE3,NEWL11,NEWU11,NGRD3,NSLU11,NVHO11,ODPV3,OFSA3,ONCO3,OPCT3,ORVR3,OUJP11,PABY11,PATC11,PATL11,PCAR3,PCIP11,PDTC3,PETR3,PETR4,PETZ3,PFIN11,PFRM3,PGMN3,PIBB11,PICE11,PINE4,PLAG11,PLAS3,PLCR11,PLPL3,PLRI11,PMLL11,PNVL3,POMO3,POMO4,PORD11,POSI3,PPEI11,PPLA11,PQDP11,PRIO3,PRNR3,PRSV11,PSEC11,PSSA3,PTBL3,PTNT3,PTNT4,PVBI11,QBTC11,QETH11,QUAL3,RADL3,RAIL3,RAIZ4,RANI3,RAPT3,RAPT4,RBDS11,RBHY11,RBIR11,RBRD11,RBRF11,RBRL11,RBRP11,RBRR11,RBRS11,RBRY11,RBVA11,RCFA11,RCRB11,RCSL3,RCSL4,RDOR3,RECR11,RECT11,RECV3,RELG11,RENT3,RFOF11,RNDP11,RNGO11,ROMI3,RSUL4,RZAK11,RZTR11,SADI11,SANB11,SANB3,SANB4,SAPR11,SAPR3,SAPR4,SARE11,SBFG3,SBSP3,SCAR3,SCPF11,SEER3,SEQL3,SEQR11,SHOW3,SHPH11,SHUL4,SIMH3,SLCE3,SMAC11,SMAL11,SMFT3,SMTO3,SNFF11,SOJA3,SPTW11,SPXI11,SUZB3,TAEE11,TAEE3,TAEE4,TASA3,TASA4,TCSA3,TECK11,TECN3,TELB3,TELB4,TEND3,TEPP11,TFCO4,TGAR11,TGMA3,TIMS3,TOKY3,TORD11,TOTS3,TPIS3,TRAD3,TRIS3,TRNT11,TRUE11,TRXF11,TTEN3,TUPY3,UCAS3,UGPA3,UNIP3,UNIP5,UNIP6,URPR11,USIM3,USIM5,USTK11,VALE3,VAMO3,VCJR11,VCRR11,VGHF11,VGIP11,VGIR11,VIFI11,VIGT11,VILG11,VINO11,VISC11,VIUR11,VIVA3,VIVT3,VLID3,VOTS11,VPPR11,VRTA11,VSHO11,VSLH11,VTLT11,VULC3,VVEO3,WDCN3,WEGE3,WEST3,WHRL3,WHRL4,WLMM4,WPLZ11,XBOV11,XFIX11,XINA11,XLPR11,XPCI11,XPCM11,XPID11,XPIE11,XPIN11,XPLG11,XPML11,XPSF11,YDUQ3
Ticker,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AALR3,1.000000,0.251346,0.026865,0.210179,-0.094798,0.063330,-0.025411,0.034997,0.080588,0.041146,0.084597,0.088447,0.163166,0.197113,0.061433,0.224129,0.101187,0.148986,0.020277,0.187219,0.204480,0.127811,0.006729,0.012074,0.015243,-0.022595,0.196144,0.194896,0.072563,0.055931,0.141258,-0.048928,-0.059160,0.101833,0.184140,0.183342,0.200978,0.189457,0.027622,0.169961,0.107508,0.278831,0.135090,0.009109,0.075771,0.148869,-0.009543,-0.014329,-0.065754,0.112451,0.143391,0.061601,-0.075385,0.149382,-0.047656,-0.064614,-0.028367,-0.045392,-0.030620,0.066196,0.015133,-0.039110,-0.053973,-0.048898,-0.045575,-0.006519,-0.002550,0.145448,0.034899,0.111505,0.225453,0.004127,0.063844,-0.061949,0.123330,-0.089723,0.084781,0.271520,0.291854,0.277076,0.138730,0.108632,0.051221,0.042164,0.037261,0.055843,0.052262,0.270030,0.073378,0.133270,0.076410,0.158425,0.173789,0.062167,0.227165,0.008531,-0.048091,-0.002860,0.119545,0.021913,0.126631,0.093038,0.058964,0.003427,0.062145,0.024021,0.250863,0.021509,0.005735,-0.002329,0.015842,0.128599,0.099054,0.124632,0.098425,0.131870,0.090490,0.197647,0.216324,0.069824,0.041017,0.117536,0.249970,0.209481,0.127642,0.083480,0.078226,0.011115,-0.000521,0.103013,0.116640,0.136819,0.163429,0.144243,0.142186,0.037846,0.000634,0.168901,0.231126,-0.014865,0.035296,0.087139,0.046321,0.270385,0.057018,0.125865,-0.010472,0.017787,0.193433,0.281844,0.092133,-0.006530,0.031281,0.044896,0.297370,0.231497,0.152003,0.165581,0.079007,0.145935,-0.033229,0.243449,0.106502,0.181992,0.104164,0.133782,0.118515,0.194556,0.068637,0.008929,0.161913,0.067313,0.268689,0.237048,0.146042,0.024623,0.014385,0.077966,0.122163,0.129132,0.227858,0.120982,0.023653,-0.036218,-0.009300,0.043770,0.078524,0.186573,0.052509,0.026218,0.017784,0.199598,0.067859,0.111766,0.018915,0.040962,0.026630,0.096071,0.083668,0.144615,0.134676,0.131255,0.030001,0.150898,0.175832,0.144456,0.003987,-0.086949,0.252351,0.148148,0.104635,0.058621,0.106831,0.141263,0.116065,0.007232,0.104747,0.049079,0.016300,0.194913,0.093240,0.092818,0.073864,0.023808,0.035467,0.029061,0.024894,0.149258,-0.001383,0.044874,0.086881,0.030965,0.158567,0.020079,0.049906,0.067562,0.032329,-0.029914,0.027960,0.008165,0.166362,-0.038254,0.106796,-0.024886,0.218373,-0.002312,0.025877,0.132073,0.080720,0.079441,0.249664,0.179545,0.209051,0.178649,0.175782,0.015951,0.065609,0.088202,0.043030,0.218626,0.075072,0.216084,0.080080,0.038193,0.084227,0.098588,0.005244,0.095700,0.038156,0.095403,0.111521,0.095437,0.072312,0.037513,0.141169,-0.003203,0.007857,0.146543,0.165262,-0.004631,0.126461,0.209069,0.195448,0.180979,0.236497,0.117970,0.136128,0.135443,0.125122,0.031076,0.098679,0.138095,0.239520,0.230894,0.073519,0.101512,-0.025846,0.054897,-0.059574,0.190574,0.137199,0.063855,0.028078,0.235835,0.222462,0.125624,0.247681,0.260897,0.090524,0.163779,0.020925,0.252786,-0.060461,0.160743,0.016066,0.213423,0.098958,0.021835,0.027507,0.070356,0.010508,0.141239,0.183037,0.073407,0.116393,0.139673,0.109899,0.022833,0.114319,0.036197,0.080978,0.112818,0.111934,0.185624,0.187878,0.150094,0.075388,0.211362,0.105485,0.274831,-0.051931,0.143387,0.083262,0.065469,0.120873,0.096674,0.023840,0.161452,0.091236,0.231651,0.233429,0.028740,0.192551,-0.033827,-0.056200,0.050732,0.097128,0.216500,0.045484,0.110097,0.126564,0.212410,0.038524,0.093597,0.039705,0.026082,0.024549,0.224151,0.055628,0.189623,0.094954,0.116693,0.225461,0.241797,0.023469,-0.032429,-0.012981,0.080409,0.019831,0.017329,0.132932,0.099820,0.040813,0.023148,0.020284,0.005357,0.043493,0.048414,0.084625,0.158155,-0.012522,0.076805,0.038597,0.011728,0.173939,0.114892,0.025717,0.120437,0.173630,0.048898,-0.007128,0.053110,0.031910,0.205404,0.172529,0.191551,0.173214,0.146790,0.168930,0.041557,0.182901,0.209565,0.140338,0.028514,0.193115,0.004875,-0.038195,0.114883,0.079437,0.144953,0.141918,0.087329,0.341079,0.330657,0.144276,0.132658,0.036373,0.066732,0.078158,0.011106,0.026032,0.176835,0.113065,0.138390,0.187769,0.172023,0.131456,-0.030265,0.155215,0.027850,0.065032,0.218581,-0.020237,0.114552,0.118267,0.212521,0.096096,0.137188,0.017655,0.191780,0.116348,0.035001,0.235609,0.007727,-0.006476,0.078757,0.106369,0.151160,0.162877,0.187140,0.107112,0.118149,0.163123,0.051574,0.140696,0.146504,-0.031583,0.102522,-0.005039,0.091947,0.082948,0.048501,0.065292,0.018816,-0.000329,0.048118,0.123416,0.048435,0.159334,0.007365,0.304334,0.091231,0.178729,0.078514,0.095580,0.110007,0.106092,0.029917,0.108337,0.200527,0.085818,0.101530,0.139436,0.040435,0.109566,0.135815,0.066905,0.076450,0.281164,0.013118,0.003518,0.014866,0.082983,0.049269,0.050243,0.067379,0.080953,0.156297,0.177013,0.025888,0.222279
ABCB4,0.251346,1.000000,0.049417,0.304478,-0.071821,0.074478,0.024415,0.093628,0.243638,0.067411,0.166631,0.129262,0.232936,0.315387,0.147353,0.353791,0.186438,0.244491,0.049347,0.279812,0.297200,0.293814,0.106418,0.017417,0.130339,0.044364,0.400081,0.391982,0.068248,0.054867,0.331481,-0.072447,-0.032637,0.130954,0.033550,0.499329,0.505761,0.518083,0.085160,0.500732,0.132660,0.580547,0.380851,-0.003560,0.093790,0.176243,0.033859,0.028602,-0.079442,0.209038,0.093958,0.077936,-0.115063,0.115871,-0.104644,-0.081952,-0.042627,-0.050572,-0.027977,0.108910,-0.009468,-0.052029,-0.048985,-0.084705,-0.041938,0.000296,-0.035186,0.208537,0.015178,0.111198,0.414190,0.085027,0.098877,0.074289,0.293510,-0.091952,0.152294,0.587534,0.629879,0.612660,0.486501,0.353668,0.174144,0.250803,0.062842,0.245060,0.247553,0.590198,0.187965,0.180753,0.179764,0.259182,0.284703,0.118331,0.495700,0.083697,-0.030927,0.014152,0.266006,0.018833,0.202110,0.303269,0.064550,0.133822,0.192023,0.022449,0.402965,0.035057,-0.008850,-0.002670,0.148557,0.163351,0.073569,0.185196,0.145271,0.245294,0.190896,0.382966,0.421066,0.245940,0.038958,0.205111,0.427254,0.343830,0.261632,0.197689,0.025128,0.026665,0.083695,0.145906,0.120058,0.257116,0.242333,0.251932,0.345223,0.073765,0.020892,0.307799,0.400020,0.041264,0.054917,0.304393,0.094115,0.492952,0.165536,0.272591,-0.017631,0.144932,0.318520,0.586577,0.183637,0.087500,0.069814,0.149421,0.567990,0.430659,0.173559,0.325344,0.157712,0.239163,0.055925,0.404709,0.160144,0.257271,0.207852,0.282432,0.183001,0.487783,0.258934,0.112017,0.239392,0.146535,0.444911,0.454993,0.207363,-0.001150,0.043162,0.161037,0.174499,0.137354,0.583987,0.265247,0.030141,0.032807,-0.008232,0.026500,0.096203,0.293630,0.091882,0.004850,0.039460,0.295985,0.074682,0.172353,0.002844,0.108484,0.001711,0.124620,0.141781,0.320318,0.344874,0.309760,0.033638,0.303097,0.361057,0.367193,-0.008661,-0.208381,0.550406,0.249890,0.135897,0.069623,0.159012,0.253589,0.188539,0.077877,0.155622,0.134329,0.002404,0.291112,0.204949,0.227650,0.084767,0.039850,0.021616,0.033894,0.022075,0.213852,-0.000519,0.033348,0.078267,0.064784,0.240557,-0.009406,0.079023,0.085114,0.041931,-0.022628,0.068870,0.080230,0.268190,-0.069065,0.163494,-0.009867,0.333218,0.097113,0.060795,0.279053,0.137025,0.147592,0.528633,0.430919,0.533652,0.479248,0.497136,-0.007495,0.236164,0.210013,0.053352,0.389278,0.137774,0.363552,0.179548,0.048718,0.166760,0.235135,0.027020,0.175863,0.106443,0.174797,0.098113,0.162852,0.115268,0.023082,0.198095,0.017236,0.098067,0.353435,0.289311,-0.002681,0.290400,0.427768,0.195924,0.327664,0.275925,0.174165,0.251257,0.312665,0.270480,0.035189,0.170049,0.187179,0.465973,0.318457,0.270673,0.117291,0.026623,0.131256,-0.019678,0.347188,0.248481,0.099369,0.042422,0.438295,0.431777,0.261199,0.405590,0.413348,0.197273,0.338628,0.046828,0.420322,-0.054823,0.304092,0.074747,0.436798,0.139753,-0.007859,0.067236,0.132994,0.035816,0.221780,0.270820,0.211365,0.200077,0.326220,0.162089,-0.017383,0.123639,0.088341,0.124571,0.162300,0.177033,0.382676,0.392791,0.250648,0.085839,0.294215,0.274696,0.591332,-0.030122,0.224227,0.117773,0.127237,0.241139,0.254383,0.034678,0.277407,0.141091,0.358062,0.363594,0.030635,0.329066,0.002465,-0.062327,0.099688,0.144310,0.318887,0.046618,0.201755,0.241805,0.326369,0.044650,0.207708,0.029803,0.009947,0.018792,0.314243,0.165489,0.425094,0.259071,0.190333,0.337111,0.440987,0.082887,0.005281,0.022378,0.114269,0.032448,0.076691,0.189447,0.176438,0.001299,0.123304,0.064652,0.048243,0.181452,0.078922,0.083423,0.309098,0.057075,0.153658,0.224571,0.037507,0.330998,0.234760,0.021617,0.157931,0.252900,-0.070228,0.012684,0.094913,0.022053,0.500839,0.403495,0.393119,0.273706,0.227359,0.266270,0.034203,0.313973,0.403665,0.209070,0.083972,0.294518,0.061590,0.072515,0.139663,0.110872,0.224055,0.188921,0.142976,0.625277,0.582477,0.359220,0.265520,0.063799,0.179510,0.122629,0.011984,0.068765,0.290612,0.193147,0.256484,0.269908,0.269774,0.234741,-0.016246,0.266062,0.064558,0.069253,0.332968,-0.015405,0.250117,0.167368,0.407618,0.259922,0.089740,-0.003774,0.297870,0.219751,0.131580,0.329254,0.059840,0.046512,0.188952,0.254597,0.291592,0.247033,0.355604,0.202986,0.086969,0.137033,0.017286,0.273050,0.352712,-0.030929,0.256157,0.228327,0.145331,0.051194,0.040804,0.161546,0.067201,0.009645,0.104706,0.215220,0.102118,0.293365,-0.034551,0.513795,0.213897,0.308074,-0.001112,0.245550,0.126140,0.195112,-0.011187,0.173735,0.224044,0.176533,0.197636,0.180501,0.048951,0.150328,0.172526,0.083640,0.086878,0.586129,0.101704,-0.008931,0.052759,0.216493,0.091749,0.070744,0.090782,0.164238,0.233741,0.266432,0.047170,0.388493
ABCP11,0.026865,0.049417,1.000000,0.058925,-0.039120,0.006754,0.051182,0.041806,0.044327,0.116111,0.043597,0.040903,0.035976,0.050333,0.050735,0.062393,0.053373,0.049430,0.020946,0.054942,0.052367,0.043300,0.009237,0.030650,0.044108,0.014066,0.041054,0.037614,0.029665,-0.013025,0.042846,-0.037977,-0.037644,0.192923,0.037208,0.048962,0.036061,0.041330,0.087620,0.076579,0.037679,0.055864,0.043311,-0.028273,0.039135,0.063863,0.026716,0.022139,-0.021406,0.023866,0.001545,0.007563,-0.036147,0.064451,0.026330,-0.031158,-0.033132,0.004748,-0.009834,0.047099,-0.022772,-0.003755,-0.011926,-0.009153,0.030713,-0.018459,-0.025326,0.074252,0.072964,-0.002394,0.183597,0.026952,0.014983,0.005609,0.077053,-0.034761,-0.043817,0.065268,0.211489,0.070637,0.086095,0.034934,0.009772,0.004388,0.020589,0.037087,0.025903,0.056532,0.029077,0.219231,0.078125,0.028560,0.034625,-0.009482,0.012933,0.082283,-0.032347,0.057712,0.238670,0.034522,0.120900,0.013316,0.001225,0.020324,0.038764,0.011130,0.143326,0.054987,0.052019,-0.001420,0.022833,0.047864,0.008191,0.028557,0.041437,0.021585,0.038462,0.052636,0.028774,0.003781,0.037221,0.044991,0.096317,0.000279,0.236065,0.016203,0.055886,0.021440,0.112885,0.070914,0.078925,0.037010,0.070327,0.042451,0.016213,0.014156,0.792378,0.057088,0.056666,0.096038,0.015382,0.050006,0.057231,0.047124,0.039952,0.018692,0.054152,0.029193,0.016319,0.053831,0.054757,0.012286,0.040410,0.012890,0.132157,0.045638,0.082184,0.049047,0.031721,0.040958,0.040448,0.048724,0.017220,0.044896,0.035386,0.130687,0.020476,0.069049,0.069258,0.042665,0.037401,0.012271,0.047071,0.058101,0.091058,-0.002813,0.013391,0.012289,0.056314,0.062379,0.041972,0.086422,0.020338,0.026037,0.049261,-0.008242,0.023465,0.023961,0.033964,0.012006,0.070913,0.052565,0.021005,0.034809,0.007622,0.017025,-0.000326,0.020436,0.046744,0.033004,0.037266,0.063518,0.014316,0.099820,0.032715,0.044488,0.003146,-0.079229,0.045436,0.032910,0.127831,0.010670,0.163522,0.037244,0.207684,0.029651,0.045952,0.013972,-0.011383,0.034468,0.051417,0.036741,0.026432,0.043095,0.016070,0.013062,0.020098,0.246477,0.053151,0.024686,0.117132,0.033166,0.086312,0.013360,0.094361,0.133256,0.021469,0.015041,0.142450,0.142810,0.267685,-0.066541,0.064015,0.061245,0.025735,0.044780,0.123057,0.078593,0.016076,0.056457,0.036261,0.056966,0.049064,0.040974,0.040926,0.020106,0.095837,0.004797,0.083397,0.054767,0.146065,0.059634,0.055434,0.064396,0.012148,0.218695,-0.017976,0.052049,0.001240,0.033874,0.058239,0.063742,0.041388,-0.012479,0.059855,0.007108,-0.009017,0.077067,0.050867,0.011049,0.039526,0.081739,0.080170,0.050411,0.059737,0.071407,0.124312,0.031606,0.070135,-0.008081,0.169727,0.016294,0.222286,0.032815,0.043228,0.069373,-0.006416,0.010633,-0.036975,0.047237,0.037521,0.046381,-0.020135,0.042404,0.049058,0.057363,0.032373,0.142026,0.073706,0.035892,0.007862,0.040284,-0.027809,0.045758,0.057117,0.141521,0.117394,0.012524,0.016795,0.026838,-0.023479,0.039162,0.035146,0.041993,0.004843,0.096013,0.043646,-0.003700,0.133807,0.157228,0.078217,0.177278,0.053116,0.049507,0.042140,0.060434,0.114293,0.043559,0.031088,0.067651,0.017509,0.062923,0.111714,0.053195,0.295765,0.044939,0.029143,0.078468,0.109469,0.028102,0.030232,0.009396,0.041651,0.016845,-0.023940,0.060546,0.038249,0.176831,0.009726,0.190346,0.023315,0.026984,0.059420,0.034634,0.160691,-0.015134,0.022540,0.033455,0.022999,0.023777,0.066492,0.035522,0.069948,0.044847,-0.037780,0.138767,-0.037723,0.031350,0.013201,0.051686,0.232312,0.122489,0.020186,0.078015,0.047759,0.018277,0.163565,0.021235,0.021711,0.019681,0.102711,0.183536,0.065319,0.103763,0.023987,0.280620,0.031805,0.074198,0.030408,0.003554,0.043683,0.150390,0.035881,0.050091,0.024903,0.046079,0.081361,0.072799,0.050145,0.050346,0.056859,0.063983,0.054102,0.014660,0.027988,0.026999,0.034633,0.006386,0.050288,0.035271,0.062631,0.004990,0.246701,0.069806,0.080856,0.040106,0.073003,0.018084,0.069582,0.017061,0.026613,0.042348,0.010167,0.035358,0.124563,0.135404,0.042835,-0.035902,0.039085,0.019710,0.009516,0.015059,0.005978,0.042699,0.054995,0.063855,-0.006019,0.119841,0.120604,0.027865,0.060668,0.047118,0.072855,0.029122,-0.026007,0.164870,0.076460,0.077030,0.048211,0.032837,0.051301,0.037660,0.048769,0.127134,0.026099,0.025911,-0.038625,0.029487,0.065550,0.177106,0.067392,0.149870,0.166564,0.016306,0.010053,0.061501,0.252895,0.104714,0.108515,-0.009919,0.206642,0.040980,0.048428,0.015457,0.255821,0.070853,0.089234,0.011288,0.177334,0.000516,0.042611,0.011640,0.055518,-0.055700,0.044315,0.021740,0.032651,0.031418,0.063099,0.151586,-0.021615,0.023228,0.282978,0.050358,0.072141,0.102485,0.113433,0.065030,0.109342,0.024562,0.163246

In [13]:
corr_matrix.to_parquet('data/processed/corr_matrix.parquet')

In [14]:
import yfinance as yf
import time
from requests.exceptions import HTTPError

cm = pd.read_parquet('data/processed/corr_matrix.parquet')
tickers = cm.columns.tolist()
setores = []


def to_yahoo_symbol(ticker: str) -> str:
    t = str(ticker).strip().upper()
    if t.endswith(".SA"):
        return t
    return f"{t}.SA"


for ticker in tickers:
    yahoo_sym = to_yahoo_symbol(ticker)
    try:
        empresa = yf.Ticker(yahoo_sym)
        setor = empresa.info.get("sector")
    except HTTPError as e:
        print(f"Erro ao obter o setor para {ticker} ({yahoo_sym}): {e}")
        setor = None
    except Exception as e:
        print(f"Erro ao obter o setor para {ticker} ({yahoo_sym}): {e}")
        setor = None
    setores.append({"ticker": ticker, "setor": setor, "yahoo_symbol": yahoo_sym}) 
    time.sleep(0.5)

HTTP Error 404:
HTTP Error 404:
HTTP Error 404:
HTTP Error 404:
HTTP Error 404:

In [15]:
# removidos da bolsa
# AZUL4	
# BPAN4	
# BPFF11
# BRFS3	
# BTEK11
# CCRO3	
# CLSA3
# CPLE5
# CPLE6
# CRFB3
# ELMD3
# EXCO32
# GOLL4
# GPIV33
# KRSA3
# LIPR3
# MOAR3
# NFTS11
# PORT3
# PULV11
# RBED11
# RDNI3
# SRNA3
# STBP3
# STOC31
# ZAMP3

In [16]:
df_setores = pd.DataFrame(setores)
mask_etf = df_setores['ticker'].str.endswith('39')
df_setores.loc[mask_etf, 'setor'] = 'ETF'
mask_fii = df_setores['ticker'].str.endswith('11')
df_setores.loc[mask_fii, 'setor'] = 'Real Estate'
df_setores.loc[df_setores['ticker'] == 'FOOD11', 'setor'] = 'ETF'
df_setores.loc[df_setores['ticker'] == 'GUAR3', 'setor'] = 'Apparel Manufacturing'
df_setores.loc[df_setores['ticker'] == 'PETZ3', 'setor'] = 'Personal Services'
df_setores.loc[df_setores['ticker'] == 'PSVM11', 'setor'] = 'Marine Shipping'
df_setores.loc[df_setores['ticker'] == 'VSTE3', 'setor'] = 'Apparel Retail'
df_setores.loc[df_setores['ticker'] == 'MRFG3', 'setor'] = 'Packaged Foods'
df_setores.loc[df_setores['ticker'] == 'EVTC31', 'setor'] = 'Technology'

df_setores[df_setores['setor'].isna()]

Empty DataFrame
Columns: [ticker, setor, yahoo_symbol]
Index: []

In [17]:
df_setores.to_parquet('data/processed/df_setores.parquet')